config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :tasks do
    member do
      patch :move
    end
  end

  root to: "projects#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, -> { order(position: :asc) }, dependent: :destroy

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  acts_as_list scope: :project, add_new_at: :bottom
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    respond_to do |format|
      format.js
    end
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        # format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.js
        # format.json { render :show, status: :created, location: @project }
      else
        format.js { render status: 422 }
        # format.html { render :new }
        # format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.js
        # format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        # format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.js
      # format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :move]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
    respond_to do |format|
      format.js
    end
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.js
        # format.html { redirect_to @task, notice: 'Task was successfully created.' }
        # format.json { render :show, status: :created, location: @task }
      else
        format.js { render status: 422 }
        # format.html { render :new }
        # format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    # binding.pry
    respond_to do |format|
      if @task.update(task_params)
        format.js
      else
        format.js { render status: 422 }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.js
      # format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  def move
    @task.insert_at(params[:position].to_i)
    head :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:id, :name, :status, :project_id, :position, :deadline)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TODO list Ruby Garage</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;500;700&display=swap" rel="stylesheet">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>

<div class="wrap">

  <h1>Simple TODO LISTS</h1>
  <small>FROM RUBY GARAGE</small>

  <%= yield %>

</div>




<script
  src="https://code.jquery.com/jquery-2.2.4.min.js"
  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous"></script>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, html:{class: "add_project"}) do |form| %>
  <%= form.text_field :name, placeholder: "Enter project name"%>
  <%= form.submit 'Add Project'%>
<% end %>

app/views/projects/_project.html.erb
<div class="todo_item" id="<%="project_#{project.id}" %>">

  <div class="todo_item__head">
    <div class="head_titl"><%= project.name %></div>
    <div class="head_icons">
      <%= link_to 'Edit',  edit_project_path(project), remote: true %>
      <%= link_to 'Destroy', project, remote: true, method: :delete,  data: { confirm: 'Are you sure?' } %>
    </div>
  </div>

  <div class="todo_item__add">
    <%= form_with model: Task.new, html:{class: 'add_form'},
                  remote: true do |form| %>
      <%= form.hidden_field :project_id, value: project.id %>
      <div class="form_field">
        <%= form.text_field :name, placeholder: "Add new task name", class: "task_name"%>
      </div>
      <div class="form_field">
        <%= form.date_field :deadline, placeholder: "Add deadline", class: "task_name"%>
      </div>
      <div class="form_field">
        <%= form.submit 'Add Task'%>
      </div>
    <% end %>
  </div>

  <div class="todo_item__list" id="list<%=project.id %>"
       data-controller="drag"
       data-drag-url="/tasks/:id/move"
  >
    <% project.tasks.each do |task| %>
      <%= render('tasks/task', task: task) %>
    <% end %>
  </div>

</div>

app/views/projects/_update_form.erb
<%= form_with(model: project, remote: true, html:{class: "add_project rename"}) do |form| %>
  <%= form.text_field :name, placeholder: @project.name%>
  <%= form.submit 'Rename'%>
<% end %>

app/views/projects/create.js.erb
var projects = document.querySelector("#projects");
projects.insertAdjacentHTML("beforeend", "<%= j render(@project) %>");

document.querySelector("#project_name").value = '';
document.querySelector("form.add_project").classList.remove("open");

var btn = document.querySelector(".btn_addtem");
btn.style.marginRight = 'auto';
btn.style.display = 'block';

app/views/projects/destroy.js.erb
document.querySelector("#project_<%=@project.id %>").remove();

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/edit.js.erb
$('#project_<%=@project.id %> .head_titl')
    .html('<%= j render 'update_form', project: @project %>');

app/views/projects/index.html.erb
<!-- TODO list -->
<div class="todo_wrap" id="projects">
  <%#= render @projects %>
  <% @projects.each do |project| %>
    <%= render('projects/project', project: project) %>
    <!-- todo item -->
  <% end %>

</div><!-- /. TODO list -->

<div class="add_wrap">
  <a href="#" class="btn_addtem">Add Project</a>
  <%= render 'form', project: Project.new %>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/projects/update.js.erb
$('#project_<%=@project.id %> .head_titl').html('<%=@project.name %>');

app/views/tasks/_checkbox.html.erb
<% if task.status == true %>
  <input type="checkbox"
       data-url="<%=task_path(task)%>"
       data-params="task[status=<%= !task.status %>"
       data-remote="true"
       data-method="put" id="item<%=task.id %>" checked>
<% else %>
  <input type="checkbox"
         data-url="<%=task_path(task)%>"
         data-params="task[status=<%= !task.status %>"
         data-remote="true"
         data-method="put" id="item<%=task.id %>">
<% end %>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.text_field :id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.text_field :project_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<!-- item row -->
<div class="item_row <%= task.status ? 'done' : '' %>"
     id="<%="task_#{task.id}" %>"
     data-id="<%= task.id %>">
  <label for="item<%= task.id %>">
    <div class="item_row__inp">
      <%= render('tasks/checkbox', task: task) %>
    </div>
    <div class="item_row__text"><%=task.name %></div>
    <div class="item_row__icons">
      <%= link_to 'Edit', edit_task_path(task), remote: true, class: "link_edit" %>
      <%= link_to 'Destroy', task, remote: true, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </label>
</div><!-- /. item row -->

app/views/tasks/_update_form.erb
<%#= form_with model: task do |form| %>
  <%#= form.text_field :name %>
  <%#= form.submit %>
<%# end %>

<%= form_with model: @task, html:{class: 'rename_task'}, remote: true do |form| %>
  <%= form.hidden_field :project_id, value: @task.project.id %>
  <%= form.text_field :name, value: @task.name, class: "task_name"%>
  <%= form.date_field :deadline, value: @task.deadline, class: "task_name"%>
  <%= form.submit 'Edit Task'%>
<% end %>

app/views/tasks/create.js.erb
var wrapper = document.querySelector("#list<%=@task.project.id %>");
wrapper.insertAdjacentHTML("beforeend", "<%= j render(@task) %>");

document.querySelector("#project_<%=@task.project.id %> form .task_name").value='';

app/views/tasks/destroy.js.erb
document.querySelector("#task_<%=@task.id %>").remove();

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/edit.js.erb
$('#task_<%=@task.id %> .item_row__text')
    .html('<%= j render 'update_form', task: @task %>');

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Status</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.id %></td>
        <td><%= task.name %></td>
        <td><%= task.status %></td>
        <td><%= task.project_id %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @task.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Project:</strong>
  <%= @task.project_id %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/update.js.erb
var status = <%= !!@task.status %>

if (status == 'true')
    $('#task_<%=@task.id %>').addClass('done');
else
    $('#task_<%=@task.id %>').removeClass('done');

$('#task_<%=@task.id %> .item_row__text').html('<%=@task.name %>');
$('#task_<%=@task.id %> .item_row__inp').html('<%=j render('tasks/checkbox', task: @task) %>');